// Avoid `console` errors in browsers that lack a console.
(function(){var method;var noop=function(){};var methods=["assert","clear","count","debug","dir","dirxml","error","exception","group","groupCollapsed","groupEnd","info","log","markTimeline","profile","profileEnd","table","time","timeEnd","timeline","timelineEnd","timeStamp","trace","warn"];var length=methods.length;var console=window.console=window.console||{};while(length--){method=methods[length];
// Only stub undefined methods.
if(!console[method]){console[method]=noop}}})();/*
    A simple jQuery modal (http://github.com/kylefox/jquery-modal)
    Version 0.7.0
*/
(function($){var modals=[],getCurrent=function(){return modals.length?modals[modals.length-1]:null},selectCurrent=function(){var i,selected=false;for(i=modals.length-1;i>=0;i--){if(modals[i].$blocker){modals[i].$blocker.toggleClass("current",!selected).toggleClass("behind",selected);selected=true}}};$.modal=function(el,options){var remove,target;this.$body=$("body");this.options=$.extend({},$.modal.defaults,options);this.options.doFade=!isNaN(parseInt(this.options.fadeDuration,10));this.$blocker=null;if(this.options.closeExisting)while($.modal.isActive())$.modal.close();// Close any open modals.
modals.push(this);if(el.is("a")){target=el.attr("href");
//Select element by id from href
if(/^#/.test(target)){this.$elm=$(target);if(this.$elm.length!==1)return null;this.$body.append(this.$elm);this.open()}else{this.$elm=$("<div>");this.$body.append(this.$elm);remove=function(event,modal){modal.elm.remove()};this.showSpinner();el.trigger($.modal.AJAX_SEND);$.get(target).done(function(html){if(!$.modal.isActive())return;el.trigger($.modal.AJAX_SUCCESS);var current=getCurrent();current.$elm.empty().append(html).on($.modal.CLOSE,remove);current.hideSpinner();current.open();el.trigger($.modal.AJAX_COMPLETE)}).fail(function(){el.trigger($.modal.AJAX_FAIL);var current=getCurrent();current.hideSpinner();modals.pop();// remove expected modal from the list
el.trigger($.modal.AJAX_COMPLETE)})}}else{this.$elm=el;this.$body.append(this.$elm);this.open()}};$.modal.prototype={constructor:$.modal,open:function(){var m=this;this.block();if(this.options.doFade){setTimeout(function(){m.show()},this.options.fadeDuration*this.options.fadeDelay)}else{this.show()}$(document).off("keydown.modal").on("keydown.modal",function(event){var current=getCurrent();if(event.which==27&&current.options.escapeClose)current.close()});if(this.options.clickClose)this.$blocker.click(function(e){if(e.target==this)$.modal.close()})},close:function(){modals.pop();this.unblock();this.hide();if(!$.modal.isActive())$(document).off("keydown.modal")},block:function(){this.$elm.trigger($.modal.BEFORE_BLOCK,[this._ctx()]);this.$body.css("overflow","hidden");this.$blocker=$('<div class="jquery-modal blocker current"></div>').appendTo(this.$body);selectCurrent();if(this.options.doFade){this.$blocker.css("opacity",0).animate({opacity:1},this.options.fadeDuration)}this.$elm.trigger($.modal.BLOCK,[this._ctx()])},unblock:function(now){if(!now&&this.options.doFade)this.$blocker.fadeOut(this.options.fadeDuration,this.unblock.bind(this,true));else{this.$blocker.children().appendTo(this.$body);this.$blocker.remove();this.$blocker=null;selectCurrent();if(!$.modal.isActive())this.$body.css("overflow","")}},show:function(){this.$elm.trigger($.modal.BEFORE_OPEN,[this._ctx()]);if(this.options.showClose){this.closeButton=$('<a href="#close-modal" rel="modal:close" class="close-modal '+this.options.closeClass+'">'+this.options.closeText+'<div class="close-modal-wrapper"><div class="close-modal-left"></div><div class="close-modal-right"></div></div>'+"</a>");//making a change here - Kameron
this.$elm.append(this.closeButton)}this.$elm.addClass(this.options.modalClass).appendTo(this.$blocker);if(this.options.doFade){this.$elm.css("opacity",0).show().animate({opacity:1},this.options.fadeDuration)}else{this.$elm.show()}this.$elm.trigger($.modal.OPEN,[this._ctx()])},hide:function(){this.$elm.trigger($.modal.BEFORE_CLOSE,[this._ctx()]);if(this.closeButton)this.closeButton.remove();var _this=this;if(this.options.doFade){this.$elm.fadeOut(this.options.fadeDuration,function(){_this.$elm.trigger($.modal.AFTER_CLOSE,[_this._ctx()])})}else{this.$elm.hide(0,function(){_this.$elm.trigger($.modal.AFTER_CLOSE,[_this._ctx()])})}this.$elm.trigger($.modal.CLOSE,[this._ctx()])},showSpinner:function(){if(!this.options.showSpinner)return;this.spinner=this.spinner||$('<div class="'+this.options.modalClass+'-spinner"></div>').append(this.options.spinnerHtml);this.$body.append(this.spinner);this.spinner.show()},hideSpinner:function(){if(this.spinner)this.spinner.remove()},
//Return context for custom events
_ctx:function(){return{elm:this.$elm,$blocker:this.$blocker,options:this.options}}};$.modal.close=function(event){if(!$.modal.isActive())return;if(event)event.preventDefault();var current=getCurrent();current.close();return current.$elm};
// Returns if there currently is an active modal
$.modal.isActive=function(){return modals.length>0};$.modal.defaults={closeExisting:true,escapeClose:true,clickClose:true,closeText:"Close",closeClass:"",modalClass:"modal",spinnerHtml:null,showSpinner:true,showClose:true,fadeDuration:null,// Number of milliseconds the fade animation takes.
fadeDelay:1};
// Event constants
$.modal.BEFORE_BLOCK="modal:before-block";$.modal.BLOCK="modal:block";$.modal.BEFORE_OPEN="modal:before-open";$.modal.OPEN="modal:open";$.modal.BEFORE_CLOSE="modal:before-close";$.modal.CLOSE="modal:close";$.modal.AFTER_CLOSE="modal:after-close";$.modal.AJAX_SEND="modal:ajax:send";$.modal.AJAX_SUCCESS="modal:ajax:success";$.modal.AJAX_FAIL="modal:ajax:fail";$.modal.AJAX_COMPLETE="modal:ajax:complete";$.fn.modal=function(options){if(this.length===1){new $.modal(this,options)}return this};
// Automatically bind links with rel="modal:close" to, well, close the modal.
$(document).on("click.modal",'a[rel="modal:close"]',$.modal.close);$(document).on("click.modal",'a[rel="modal:open"]',function(event){event.preventDefault();$(this).modal()})})(jQuery);$(function(){var hamburgerWrap=$("#navbar-mobile-wrapper"),hamburger=$(".navbar-mobile-hamburger"),menu=$("#navbar-menu-wrapper"),navbar=$("#navbar"),body=$("body"),toggleMenu=function(){menu.toggleClass("js-active")},toggleHamburger=function(){hamburger.toggleClass("js-active")};hamburgerWrap.on("click",toggleMenu);hamburgerWrap.on("click",toggleHamburger);hamburgerWrap.on("click",function(){navbar.toggleClass("js-active-modal")});hamburgerWrap.on("click",function(){body.toggleClass("js-active-overflow")})});$(function(){var navbar=$(".navbar-container"),whileScrolling=function(){var screen=$(window).scrollTop(),offset=$(".container-main").offset().top;if(screen-offset>=0){navbar.addClass("js-active-scrolling")}else{navbar.removeClass("js-active-scrolling")}};$(document).on("scroll",whileScrolling)});$(function(){var menu=$("#navbar-menu-wrapper"),hamburger=$(".navbar-mobile-hamburger"),topNavHeight=$("#navbar > .navbar-container").height(),navbar=$("#navbar"),body=$("body");$(".smooth-scroll-link").click(function(){menu.removeClass("js-active");hamburger.removeClass("js-active");navbar.removeClass("js-active-modal");body.removeClass("js-active-overflow");$("html, body").animate({scrollTop:$($(this).attr("href")).offset().top-topNavHeight/2},1e3);return false})});$(function(){var readmoreContainer=$(".readmore-container"),readmoreAddClass=function(){$(this).prev(".readmore-container").slideToggle(500,function(){$(this).next(".readmore-button").remove();$(this).addClass("js-visible")})};$(".readmore-button").on("click",readmoreAddClass)});